name: Call a reusable workflow

on:
  push:

jobs:
  call-workflow:
    uses: nachoesmite/workflow-lib/.github/test-inputs.yaml@v136703331e6ef2906fcedb059a7174f015763975e
    with:
      config-path: .github/labeler.yml

