name: Call a reusable workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "HELLO WORLDDDDD"
  call-workflow:
    uses: nachoesmite/workflow-lib/.github/workflows/test.yaml@main
